-- DROP TABLE IF EXISTS users;

CREATE TABLE users(
      id SERIAL PRIMARY KEY,
      first VARCHAR(255) NOT NULL,
      last VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE,
      password VARCHAR(255) NOT NULL,
      url VARCHAR,
      bio VARCHAR(255),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );

CREATE TABLE password_reset_codes(
    id SERIAL PRIMARY KEY,
    email VARCHAR,
    code VARCHAR(6),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE friendships( id SERIAL PRIMARY KEY,
     sender_id INT REFERENCES users(id) NOT NULL,
     recipient_id INT REFERENCES users(id) NOT NULL,
     accepted BOOLEAN DEFAULT false);

CREATE TABLE chat_messages(
    id SERIAL PRIMARY KEY,
    message VARCHAR NOT NULL CHECK (message <> ''),
    sender_id INT NOT NULL REFERENCES users(id),
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE feed(
    id SERIAL PRIMARY KEY,
    content VARCHAR NOT NULL CHECK (content <> ''),
    sender_id INT NOT NULL REFERENCES users(id),
    recipient_id INT REFERENCES users(id) NOT NULL,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE article(
    id SERIAL PRIMARY KEY,
    author VARCHAR(255),
    title VARCHAR,
    subline VARCHAR,
    highlights VARCHAR,
    intro VARCHAR,
    chapter VARCHAR,
    endnotes VARCHAR,
    byline VARCHAR,
    main VARCHAR,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- INSERT INTO article (author, title, subline, intro, endnotes, byline, main) VALUES (
-- 'Lara Scherrieble',
-- 'Streams over streams', 
-- 'Online-Sein zu Corona-Zeiten', 
-- 'The storm gave and the storm took away, and we should look now for its gifts before the wind dies down, the waves settle and we see a wealthy white man walking out of the water.',
-- '. Jack J. Halberstam, What the Storm Blows In (23.03.2020): bullybloggers.wordpress.com/2020/03/23/what-the-storm-blows-inby-jack-halberstam-for-bunkerbloggers/, zuletzt aufgerufen: 01.04.2020
-- . https://staythefuckhome.com/, zuletzt aufgerufen: 31.03.2020
-- . Fear Of Missing Out / Die Angst, etwas zu verpassen.
-- . Katja Grawinkel-Claassen, Der Corona-Reflex (30.03.2020): https://nachtkritik.de/index.php?option=com_content&view=article&id=17857%3Aliveness-im-digitalen-raum&catid=101&Itemid=84&fbclid=IwAR0keTRG4dly1xlw32pZTUwHosXbDGQ_nxHFa41I46fMrth7R8eRIFlWYmU, zuletzt aufgerufen: 31.03.2020
-- . International Indigenous Youth Council: https://www.facebook.com/search/top/?q=international%20indigenous%20youth%20council&epa=SEARCH_BOX, zuletzt aufgerufen: 01.04.2020.
-- . Nachdem alle Stars der kritischen Theorie von Judith Butler über Jean-Luc Nancy, Giorgio Agamben und Slavoj Žižek sich einigermaßen erfolglos daran versucht hatten. Die Texte von Cathrine Malabou (To Quarantine from Quarantine), Anne Boyer (This Virus), Jack Halberstam (What the Storm Blows In) und Paul B. Preciado (The Losers Conspiracy) sind allerdings zu empfehlen. 
-- . Cardi B, die sich ohnehin schon lange mit beinahe marxistischer Regierungskritik und feministischen Lyrics in mein Herz gesungen hatte, reagierte mit Humor auf den Remix ihres Posts. Sie kontaktierte den DJ Imarkkeyz und versprach in einem Tweet, die Einnahmen des Songs, die ihr zustünden, an weniger privilegierte Menschen als sie selbst zu spenden, die unter den Auswirkungen von Corona leiden werden.
-- . Michael Stallknecht, Die Klassikfamilie (29.03.2020): https://www.sueddeutsche.de/kultur/music-never-sleeps-nyc-die-klassikfamilie-1.4860613, zuletzt aufgerufen: 01.04.2020
-- . Ganz ähnlich übrigens in Deutschland: die wöchentlichen Hauskonzerte von Pianist Igor Levit. 
-- . Am 27. März ließ die Plattform den Künstler*innen die Beträge sogar ohne Abzüge zukommen.
-- . Auf Spotify zu finden unter: ebow.mp3 – STAY HOME AND STAY HEALTY *grünes herz*', 
-- 'Lara Scherrieble wurde als Teil des Kollektivs FAM_ angeboten, Online-Formate zu entwickeln, um die vereinbarte Gage für eine Veranstaltungsreihe im Grünen Salon trotz Ausfällen zu erhalten. Wahrscheinlich sagen sie zu. Scherrieble lebt in London und arbeitet als Teilzeit-DJ: soundcloud/some_lane  // tryniti',
-- 'Von Beginn des langsamen Einbruchs der Realität an, der irgendwann Anfang Februar mit den ersten Exponentialkurven in Artikeln über COVID-19 begann, war ich ununterbrochen online. Die Suche nach Informationen in unzähligen Artikeln wuchs zu einem hektischen Scrollen durch Twitter, Instagram, Tiktok und Facebook – wo es noch seltsam ruhig war, was die Coronavirus-Panik betraf. Dann, als das Thema überhandnahm – Toilettenpapier in Supermärkten ausverkauft und die ersten Bekannten an Husten erkrankt waren, gab es schlagartig kaum noch ein anderes Thema. Der Aufruf #staythefuckhome wurde zur sozialen Bewegung, Tweets aus linken und queeren Communities betrieben Aufklärung darüber, dass Zuhausebleiben, wenn man nicht gerade im Gesundheitswesen arbeitete, solidarisch war und nicht hypochondrisch. Der Stress, der mit der Entscheidung nicht mehr vor die Haustür zu gehen einherging, wurde abgelöst von dem Stress, mit allem on Track zu bleiben, was im Netz passierte. 
-- Empfehlungen zu Quarantäne-Aktivitäten, Fitnessanleitungen, Koch- und Backrezepten, Filme und Videogames kursierten, gleichzeitig mit Streaming-Links zu in »real life« abgesagten Lesungen, Seminaren, sogar Partys, die »auf online« verlegt werden sollten. Virtuelle Galerien eröffneten, Mitschnitte von Theaterstücken und Klassikkonzerten wurden auf Homepages veröffentlicht. Bald gab es Listen, die alle online verfügbaren Livestreams oder 24 Stunden lang verfügbare Kunstfilme sammelten, bald Verzeichnisse der Listen. Yoga from home, Online-Seminare, Virtual Reading Groups und -Hangouts: Das alles wurde zu einem völlig unübersichtlichen Kultur- und Sozialangebot. 
-- Am Anfang war ich euphorisch – aber dann, nach ein paar Tagen ständiger Online-fomo allein bei dem Gedanken daran, was ich im Netz alles konsumieren könnte, überfordert und genervt. 
-- Ich hatte den Eindruck, dass von institutioneller Seite her alles getan wurde, eine Illusion jener Normalität »vor Corona« aufrecht zu erhalten, die für viele längst Kopf stand. 
-- Leider machten besonders Veranstaltungen, die tatsächlich live stattgefunden hätten, online keinen Sinn mehr. Die mehrstündigen Uniseminare, die ich auf Jitsi »besuchte«, waren geprägt von technischen Problemen und schlechtem Sound, die Karte für das Konzert von Loraine James hatte ich gekauft, um sie live zu erleben. Auf Youtube hatte ich sie schon oft genug auf meinem Bildschirm gesehen. Dass das Konzert online gestreamt werden sollte, war irgendwie nett, aber stand in keinem Vergleich zu dem Event, auf das ich mich gefreut hatte. 
-- Laut Katja Grawinkel-Claassen bricht sich in dieser Überkompensation »der Rechtfertigungsdruck Bahnen, den öffentliche Institutionen in der neoliberalen Kultur längst vor Corona verinnerlicht haben.« Jetzt, so schreibt sie weiter, »werden häufig unausgegorene digitale Tools eingesetzt, um Angebote für das Netz zu produzieren, um die, zugespitzt gesagt, niemand gebeten hat«. Damit hat sie recht. Im Fall der Künste werden Formate, die nicht ohnehin klug mit digitalen Ästhetiken arbeiten, auch in einer globalen Pandemie nicht zu Netzkunst. Die Idee britischer Kunstuniversitäten, die Rundgänge ihrer Abschlussklassen auf einen Instagram-Kanal zu verlegen, rief zurecht eine Welle der Empörung hervor. Nicht alle können ihre Kunst der Onlinerezeption anpassen. Und niemand will noch mehr Content auf Instagram sehen. Schon gar nicht Content, der mit dem Medium nichts zu tun hat. Yoga einem Live-Stream am Rechner folgend, zu praktizieren, ist seltsam genug, wenn man wie ich Sport macht, um mal nicht am Bildschirm zu hängen. Und ins Theater gehe ich eigentlich auch, um auf eine andere Weise mit Bild und Ton involviert zu werden, als es Netflix-Serien auf meinem Rechner tun.
-- Gleichzeitig haben nicht nur öffentliche Institutionen neoliberale Politiken als Produktivitätsdruck verinnerlicht, sondern wir alle. Die Zeit in Quarantäne jetzt mal richtig gut nutzen, neue Sprachen lernen, mal wieder Cello spielen, sich den »Sommerbody« antrainieren, nach dem ganzen Tag im Homeoffice Kunst konsumieren und Texte runterladen, die sonst hinter Paywalls stehen – zum Glück wurde diese Haltung schnell in sämtlichen Memes als schlecht getimte Selbstoptimierung verspottet. Aber was macht man stattdessen mit der frei gewordenen Zeit?

-- Kinda feeling like the Earth just sent us all to our rooms to think about what we’ve done.
-- Dieser Satz auf der Facebook-Seite des International Indigenous Youth Council brachte mein Bedürfnis nach Ruhe zwischen gefühltem Freizeit-Overload und leichter Panik angesichts der stündlich wechselnden Informationslage auf den Punkt. Dem Ausnahmezustand in der Corona-Pandemie konnte nicht mit mehr Internet-Snacks und Kunst auf Abruf begegnet werden. Was vor Corona Normalität war – arbeiten oder zur Schule gehen, Freund*innen in Bars oder Clubs treffen etc. – war vorübergehend suspendiert. Plötzlich waren alle, die Zugang zu Basic Needs wie einem eigenen Zimmer haben, allein darin eingesperrt. Und konnten von da aus auf den vollständigen Zerfall dessen schauen, was vorher schon kaputt war. Europäische Außenpolitik. Das privatisierte Bildungs- und Gesundheitssystem. Zeitarbeit. Rassismuskritische Berichterstattung (viel zu wenig). Das Einkommen von Care-Arbeiter*innen und Künstler*innen (viel zu wenig). Etc. 
-- Dafür braucht man Zeit. Allein, um zu realisieren, dass das System um einen herum, das aus aktivistischer Perspektive oft so unumstürzlich scheint, kontingent gesetzt werden kann – in diesem Fall leider nicht durch die zahlreichen politischen Kämpfe des letzten Jahrzehnts, sondern durch eine Krankheit.  Streamen und Hören   Der erste musikalische Beitrag, der sich inhaltlich explizit auf Corona bezieht und gut geraten ist, kam aus dem Bereich der Memes und der Popmusik; aus einer zufälligen Fusion von Instagram und TikTok-Formaten. Ein (zuvor) unbekannter DJ sampelte einige Tage vor dem offiziellen Lockdown in Deutschland Cardi B, eine der erfolgreichsten US-Rapperinnen, mit einem selbstgebastelten Beat und ein paar Tanzvideos. Zu sehen ist ein kurzer Ausschnitt aus Cardi Bs Instagram Post, in dem sie, (in einem halbdurchsichtigen Kleid und azurblauen 5cm-Nägeln in ihrer Küche stehend) ruft: »Guess what bitch, ha ha ha! Coronavirus! Coronavirus! Shit is real, shit is getting real«. Dann setzt ein simpler Hip-Hop Beat ein, Cardi Bs Worte werden repetitiv dazu gemixt und die nächsten 60 Sekunden tanzen unter anderem das Krümelmonster, Beyoncé, Bugs Bunny und ein paar Privatpersonen exzessiv zu dem Song.
-- Nachdem ich das Video circa zehnmal anschauen und jedes Mal wieder lachen musste – war es vielleicht sogar das erste Mal richtig lachen seit der ersten Virus-Panikwelle? – und der Ohrwurm Shit is real, Shit is getting real mich tagelang verfolgte, war ich mir sicher: dieses auditive Meme war der bislang beste Kommentar zur aktuellen Lage. 	
-- Dass der Song Coronavirus nach ein paar Tagen auf Platz 1 der Itunes Charts in den USA landete, war nicht weiter verwunderlich.
-- Auf italienischen Balkonen wurde unterdessen zusammen gesungen, in einer Kleinstadt im Süden des Landes ein DJ-Pult mit Lightshow aufgebaut und die Straße mit Gigi D’Agostino’s Disco Hit L‘amour toujours beschallt. Während die wackeligen Aufnahmen dieser Szenen mich tatsächlich rührten, nicht nur weil ich dort aufgewachsen bin, sondern auch weil es dabei weder um den gemeinsamen Musikgeschmack der Nachbar*innen, noch um die Übertragung und Rezeption des Moments ging, war ich gegenüber Projekten, die die »Kraft der Musik« heraufbeschwörten eher skeptisch. 
-- Das Projekt Music Never Sleeps NYC zum Beispiel versammelte Stars der klassischen Musik, die eine ganze Nacht lang in einem Musik-Marathon ihre Lieblingsstücke spielten – von ihren privaten Wohnungen aus. Laut des Organisators hatten er selbst und die eingeladenen Künstler*innen damit »endlich wieder einen Lebenssinn«. Auf den ersten Blick eine ehrenvolle künstlerische Aktion, wirkt das ganze doch sehr sendungsbewusst – und hinsichtlich der wohlhabenden Teilnehmenden doch eher wie ein Charityball zu eigenen Ehren. Wenn der Sound sowieso aus der kleinen Anlage Zuhause kommt und nicht aus Instrumenten, in deren unmittelbarer Nähe ich mich befinde, funktioniert es für mich ehrlich gesagt besser, die Klaviersonate von Bach zu hören, ohne dabei in Wohnzimmer der oberen Mittelklasse zu blicken. 
-- Während Music Never Sleeps NYC einen leichten Hauch der Titanic-Band hat, die auf dem unausweichlich sinkenden Schiff tapfer weiterspielt, widersetzt sich die Balkonmusik in Italien der Annahme, dass das Schiff untergeht. Außerdem drängt sich mir bei dem Titanic-Vergleich die Frage auf, für wen das Schiff bald sinken könnte. Sicherlich nicht für reiche Klassik-Fans. 

-- Hören ohne streamen
-- Was ist also der Ausweg aus der Zwickmühle zwischen unangenehm ambitionierten Streamingprojekten einerseits und nachbarschaftlichen Physical-Distance-Jams, wenn man nicht gerade in italienischen Städten lebt? (Im italophilen Deutschland wurde ein paar Tage später etwas Ähnliches mit Beethovens »Ode an die Freude« probiert – lieber nicht angucken.) 
-- Playlisten. 
-- Und zwar entweder von Freund*innen: Zu hören, was eine gute Freundin Zuhause am liebsten hört, ist nämlich zugleich intim und eine große Hilfe, wenn man die eigene Musikauswahl schon zu oft gehört hat und keine Lust hat, stundenlang nach neuen Tracks zu suchen. Um selbst welche zu basteln: Seit romantischem CD-Brennen zu Teenzeiten haben das ja viele lange nicht mehr gemacht – kann man etwa auf Bandcamp Musik kaufen. Musiker*innen verdienen so ein wenig Geld, während sie keine Konzerte geben und hoffentlich vorübergehend von den in ein paar Ländern anberaumten Förderungspaketen leben können. 
-- Oder Playlisten, die von Künstler*innen zusammengestellt wurden – und auch ohne Corona gut gewesen wären: Der britische Produzent Dean Blunt veröffentlichte still und leise eine neue archivarische Sammlung von Aufnahmen aus den letzten acht Jahren unter dem Titel Roaches 2012-2019 auf Spotify. Michelle Gurevich stellte 7pm Selects zusammen, die Playlist ist aber auch für Morgende sehr zu empfehlen. Rapperin Ebow, Sängerin Slimgirl Fat und senu_unofficial aka beverlybarcley veröffentlichten Spotify-Playlisten mit ihren persönlichen Quarantine-Best-Ofs. The ultimate chilled house cat tunes ist gerade eine meiner Lieblingslisten, weil sich genau die Art entspannter und beruhigender Musik darin findet, die ich sonst viel zu selten höre. 
-- Playlisten trösten über Einsamkeit hinweg, aber lassen einen in Ruhe; und woanders hin schauen als auf den Laptop – z.B. auf die Straße beim Weg zum Einkauf für die kranke Nachbarin, auf den Suppentopf beim Kochen oder auf die Notizen vom Nachdenken über die Möglichkeit, aus dieser Krise etwas zu machen, das nicht auf die Wiederherstellung der kaputten Realität, wie sie vorher war, abzielt. 

-- PS: Der Online-Stream von Loraine James’ Konzert wurde abgesagt. Sie hatte anscheinend keine Lust darauf, allein in einem Raum für eine GoPro zu spielen – und verschob die »echte« Veranstaltung auf den 14. August. 
-- Dazu schrieb sie: »Ok, let’s do this for real lol *fingers crossed«. I’m with her.');


-- //! to_tsvector QUERY ///////////


INSERT INTO article (id, author, title, subline, intro, endnotes, byline, main, document_vectors) VALUES (
    2,
'Lara Scherrieble',
'Streams over streams', 
'Online-Sein zu Corona-Zeiten', 
'The storm gave and the storm took away, and we should look now for its gifts before the wind dies down, the waves settle and we see a wealthy white man walking out of the water.',
'. Jack J. Halberstam, What the Storm Blows In (23.03.2020): bullybloggers.wordpress.com/2020/03/23/what-the-storm-blows-inby-jack-halberstam-for-bunkerbloggers/, zuletzt aufgerufen: 01.04.2020
. https://staythefuckhome.com/, zuletzt aufgerufen: 31.03.2020
. Fear Of Missing Out / Die Angst, etwas zu verpassen.
. Katja Grawinkel-Claassen, Der Corona-Reflex (30.03.2020): https://nachtkritik.de/index.php?option=com_content&view=article&id=17857%3Aliveness-im-digitalen-raum&catid=101&Itemid=84&fbclid=IwAR0keTRG4dly1xlw32pZTUwHosXbDGQ_nxHFa41I46fMrth7R8eRIFlWYmU, zuletzt aufgerufen: 31.03.2020
. International Indigenous Youth Council: https://www.facebook.com/search/top/?q=international%20indigenous%20youth%20council&epa=SEARCH_BOX, zuletzt aufgerufen: 01.04.2020.
. Nachdem alle Stars der kritischen Theorie von Judith Butler über Jean-Luc Nancy, Giorgio Agamben und Slavoj Žižek sich einigermaßen erfolglos daran versucht hatten. Die Texte von Cathrine Malabou (To Quarantine from Quarantine), Anne Boyer (This Virus), Jack Halberstam (What the Storm Blows In) und Paul B. Preciado (The Losers Conspiracy) sind allerdings zu empfehlen. 
. Cardi B, die sich ohnehin schon lange mit beinahe marxistischer Regierungskritik und feministischen Lyrics in mein Herz gesungen hatte, reagierte mit Humor auf den Remix ihres Posts. Sie kontaktierte den DJ Imarkkeyz und versprach in einem Tweet, die Einnahmen des Songs, die ihr zustünden, an weniger privilegierte Menschen als sie selbst zu spenden, die unter den Auswirkungen von Corona leiden werden.
. Michael Stallknecht, Die Klassikfamilie (29.03.2020): https://www.sueddeutsche.de/kultur/music-never-sleeps-nyc-die-klassikfamilie-1.4860613, zuletzt aufgerufen: 01.04.2020
. Ganz ähnlich übrigens in Deutschland: die wöchentlichen Hauskonzerte von Pianist Igor Levit. 
. Am 27. März ließ die Plattform den Künstler*innen die Beträge sogar ohne Abzüge zukommen.
. Auf Spotify zu finden unter: ebow.mp3 – STAY HOME AND STAY HEALTY *grünes herz*', 
'Lara Scherrieble wurde als Teil des Kollektivs FAM_ angeboten, Online-Formate zu entwickeln, um die vereinbarte Gage für eine Veranstaltungsreihe im Grünen Salon trotz Ausfällen zu erhalten. Wahrscheinlich sagen sie zu. Scherrieble lebt in London und arbeitet als Teilzeit-DJ: soundcloud/some_lane  // tryniti',
'Von Beginn des langsamen Einbruchs der Realität an, der irgendwann Anfang Februar mit den ersten Exponentialkurven in Artikeln über COVID-19 begann, war ich ununterbrochen online. Die Suche nach Informationen in unzähligen Artikeln wuchs zu einem hektischen Scrollen durch Twitter, Instagram, Tiktok und Facebook – wo es noch seltsam ruhig war, was die Coronavirus-Panik betraf. Dann, als das Thema überhandnahm – Toilettenpapier in Supermärkten ausverkauft und die ersten Bekannten an Husten erkrankt waren, gab es schlagartig kaum noch ein anderes Thema. Der Aufruf #staythefuckhome wurde zur sozialen Bewegung, Tweets aus linken und queeren Communities betrieben Aufklärung darüber, dass Zuhausebleiben, wenn man nicht gerade im Gesundheitswesen arbeitete, solidarisch war und nicht hypochondrisch. Der Stress, der mit der Entscheidung nicht mehr vor die Haustür zu gehen einherging, wurde abgelöst von dem Stress, mit allem on Track zu bleiben, was im Netz passierte. 
Empfehlungen zu Quarantäne-Aktivitäten, Fitnessanleitungen, Koch- und Backrezepten, Filme und Videogames kursierten, gleichzeitig mit Streaming-Links zu in »real life« abgesagten Lesungen, Seminaren, sogar Partys, die »auf online« verlegt werden sollten. Virtuelle Galerien eröffneten, Mitschnitte von Theaterstücken und Klassikkonzerten wurden auf Homepages veröffentlicht. Bald gab es Listen, die alle online verfügbaren Livestreams oder 24 Stunden lang verfügbare Kunstfilme sammelten, bald Verzeichnisse der Listen. Yoga from home, Online-Seminare, Virtual Reading Groups und -Hangouts: Das alles wurde zu einem völlig unübersichtlichen Kultur- und Sozialangebot. 
Am Anfang war ich euphorisch – aber dann, nach ein paar Tagen ständiger Online-fomo allein bei dem Gedanken daran, was ich im Netz alles konsumieren könnte, überfordert und genervt. 
Ich hatte den Eindruck, dass von institutioneller Seite her alles getan wurde, eine Illusion jener Normalität »vor Corona« aufrecht zu erhalten, die für viele längst Kopf stand. 
Leider machten besonders Veranstaltungen, die tatsächlich live stattgefunden hätten, online keinen Sinn mehr. Die mehrstündigen Uniseminare, die ich auf Jitsi »besuchte«, waren geprägt von technischen Problemen und schlechtem Sound, die Karte für das Konzert von Loraine James hatte ich gekauft, um sie live zu erleben. Auf Youtube hatte ich sie schon oft genug auf meinem Bildschirm gesehen. Dass das Konzert online gestreamt werden sollte, war irgendwie nett, aber stand in keinem Vergleich zu dem Event, auf das ich mich gefreut hatte. 
Laut Katja Grawinkel-Claassen bricht sich in dieser Überkompensation »der Rechtfertigungsdruck Bahnen, den öffentliche Institutionen in der neoliberalen Kultur längst vor Corona verinnerlicht haben.« Jetzt, so schreibt sie weiter, »werden häufig unausgegorene digitale Tools eingesetzt, um Angebote für das Netz zu produzieren, um die, zugespitzt gesagt, niemand gebeten hat«. Damit hat sie recht. Im Fall der Künste werden Formate, die nicht ohnehin klug mit digitalen Ästhetiken arbeiten, auch in einer globalen Pandemie nicht zu Netzkunst. Die Idee britischer Kunstuniversitäten, die Rundgänge ihrer Abschlussklassen auf einen Instagram-Kanal zu verlegen, rief zurecht eine Welle der Empörung hervor. Nicht alle können ihre Kunst der Onlinerezeption anpassen. Und niemand will noch mehr Content auf Instagram sehen. Schon gar nicht Content, der mit dem Medium nichts zu tun hat. Yoga einem Live-Stream am Rechner folgend, zu praktizieren, ist seltsam genug, wenn man wie ich Sport macht, um mal nicht am Bildschirm zu hängen. Und ins Theater gehe ich eigentlich auch, um auf eine andere Weise mit Bild und Ton involviert zu werden, als es Netflix-Serien auf meinem Rechner tun.
Gleichzeitig haben nicht nur öffentliche Institutionen neoliberale Politiken als Produktivitätsdruck verinnerlicht, sondern wir alle. Die Zeit in Quarantäne jetzt mal richtig gut nutzen, neue Sprachen lernen, mal wieder Cello spielen, sich den »Sommerbody« antrainieren, nach dem ganzen Tag im Homeoffice Kunst konsumieren und Texte runterladen, die sonst hinter Paywalls stehen – zum Glück wurde diese Haltung schnell in sämtlichen Memes als schlecht getimte Selbstoptimierung verspottet. Aber was macht man stattdessen mit der frei gewordenen Zeit?

Kinda feeling like the Earth just sent us all to our rooms to think about what we’ve done.
Dieser Satz auf der Facebook-Seite des International Indigenous Youth Council brachte mein Bedürfnis nach Ruhe zwischen gefühltem Freizeit-Overload und leichter Panik angesichts der stündlich wechselnden Informationslage auf den Punkt. Dem Ausnahmezustand in der Corona-Pandemie konnte nicht mit mehr Internet-Snacks und Kunst auf Abruf begegnet werden. Was vor Corona Normalität war – arbeiten oder zur Schule gehen, Freund*innen in Bars oder Clubs treffen etc. – war vorübergehend suspendiert. Plötzlich waren alle, die Zugang zu Basic Needs wie einem eigenen Zimmer haben, allein darin eingesperrt. Und konnten von da aus auf den vollständigen Zerfall dessen schauen, was vorher schon kaputt war. Europäische Außenpolitik. Das privatisierte Bildungs- und Gesundheitssystem. Zeitarbeit. Rassismuskritische Berichterstattung (viel zu wenig). Das Einkommen von Care-Arbeiter*innen und Künstler*innen (viel zu wenig). Etc. 
Dafür braucht man Zeit. Allein, um zu realisieren, dass das System um einen herum, das aus aktivistischer Perspektive oft so unumstürzlich scheint, kontingent gesetzt werden kann – in diesem Fall leider nicht durch die zahlreichen politischen Kämpfe des letzten Jahrzehnts, sondern durch eine Krankheit.  Streamen und Hören   Der erste musikalische Beitrag, der sich inhaltlich explizit auf Corona bezieht und gut geraten ist, kam aus dem Bereich der Memes und der Popmusik; aus einer zufälligen Fusion von Instagram und TikTok-Formaten. Ein (zuvor) unbekannter DJ sampelte einige Tage vor dem offiziellen Lockdown in Deutschland Cardi B, eine der erfolgreichsten US-Rapperinnen, mit einem selbstgebastelten Beat und ein paar Tanzvideos. Zu sehen ist ein kurzer Ausschnitt aus Cardi Bs Instagram Post, in dem sie, (in einem halbdurchsichtigen Kleid und azurblauen 5cm-Nägeln in ihrer Küche stehend) ruft: »Guess what bitch, ha ha ha! Coronavirus! Coronavirus! Shit is real, shit is getting real«. Dann setzt ein simpler Hip-Hop Beat ein, Cardi Bs Worte werden repetitiv dazu gemixt und die nächsten 60 Sekunden tanzen unter anderem das Krümelmonster, Beyoncé, Bugs Bunny und ein paar Privatpersonen exzessiv zu dem Song.
Nachdem ich das Video circa zehnmal anschauen und jedes Mal wieder lachen musste – war es vielleicht sogar das erste Mal richtig lachen seit der ersten Virus-Panikwelle? – und der Ohrwurm Shit is real, Shit is getting real mich tagelang verfolgte, war ich mir sicher: dieses auditive Meme war der bislang beste Kommentar zur aktuellen Lage. 	
Dass der Song Coronavirus nach ein paar Tagen auf Platz 1 der Itunes Charts in den USA landete, war nicht weiter verwunderlich.
Auf italienischen Balkonen wurde unterdessen zusammen gesungen, in einer Kleinstadt im Süden des Landes ein DJ-Pult mit Lightshow aufgebaut und die Straße mit Gigi D’Agostino’s Disco Hit L‘amour toujours beschallt. Während die wackeligen Aufnahmen dieser Szenen mich tatsächlich rührten, nicht nur weil ich dort aufgewachsen bin, sondern auch weil es dabei weder um den gemeinsamen Musikgeschmack der Nachbar*innen, noch um die Übertragung und Rezeption des Moments ging, war ich gegenüber Projekten, die die »Kraft der Musik« heraufbeschwörten eher skeptisch. 
Das Projekt Music Never Sleeps NYC zum Beispiel versammelte Stars der klassischen Musik, die eine ganze Nacht lang in einem Musik-Marathon ihre Lieblingsstücke spielten – von ihren privaten Wohnungen aus. Laut des Organisators hatten er selbst und die eingeladenen Künstler*innen damit »endlich wieder einen Lebenssinn«. Auf den ersten Blick eine ehrenvolle künstlerische Aktion, wirkt das ganze doch sehr sendungsbewusst – und hinsichtlich der wohlhabenden Teilnehmenden doch eher wie ein Charityball zu eigenen Ehren. Wenn der Sound sowieso aus der kleinen Anlage Zuhause kommt und nicht aus Instrumenten, in deren unmittelbarer Nähe ich mich befinde, funktioniert es für mich ehrlich gesagt besser, die Klaviersonate von Bach zu hören, ohne dabei in Wohnzimmer der oberen Mittelklasse zu blicken. 
Während Music Never Sleeps NYC einen leichten Hauch der Titanic-Band hat, die auf dem unausweichlich sinkenden Schiff tapfer weiterspielt, widersetzt sich die Balkonmusik in Italien der Annahme, dass das Schiff untergeht. Außerdem drängt sich mir bei dem Titanic-Vergleich die Frage auf, für wen das Schiff bald sinken könnte. Sicherlich nicht für reiche Klassik-Fans. 

Hören ohne streamen
Was ist also der Ausweg aus der Zwickmühle zwischen unangenehm ambitionierten Streamingprojekten einerseits und nachbarschaftlichen Physical-Distance-Jams, wenn man nicht gerade in italienischen Städten lebt? (Im italophilen Deutschland wurde ein paar Tage später etwas Ähnliches mit Beethovens »Ode an die Freude« probiert – lieber nicht angucken.) 
Playlisten. 
Und zwar entweder von Freund*innen: Zu hören, was eine gute Freundin Zuhause am liebsten hört, ist nämlich zugleich intim und eine große Hilfe, wenn man die eigene Musikauswahl schon zu oft gehört hat und keine Lust hat, stundenlang nach neuen Tracks zu suchen. Um selbst welche zu basteln: Seit romantischem CD-Brennen zu Teenzeiten haben das ja viele lange nicht mehr gemacht – kann man etwa auf Bandcamp Musik kaufen. Musiker*innen verdienen so ein wenig Geld, während sie keine Konzerte geben und hoffentlich vorübergehend von den in ein paar Ländern anberaumten Förderungspaketen leben können. 
Oder Playlisten, die von Künstler*innen zusammengestellt wurden – und auch ohne Corona gut gewesen wären: Der britische Produzent Dean Blunt veröffentlichte still und leise eine neue archivarische Sammlung von Aufnahmen aus den letzten acht Jahren unter dem Titel Roaches 2012-2019 auf Spotify. Michelle Gurevich stellte 7pm Selects zusammen, die Playlist ist aber auch für Morgende sehr zu empfehlen. Rapperin Ebow, Sängerin Slimgirl Fat und senu_unofficial aka beverlybarcley veröffentlichten Spotify-Playlisten mit ihren persönlichen Quarantine-Best-Ofs. The ultimate chilled house cat tunes ist gerade eine meiner Lieblingslisten, weil sich genau die Art entspannter und beruhigender Musik darin findet, die ich sonst viel zu selten höre. 
Playlisten trösten über Einsamkeit hinweg, aber lassen einen in Ruhe; und woanders hin schauen als auf den Laptop – z.B. auf die Straße beim Weg zum Einkauf für die kranke Nachbarin, auf den Suppentopf beim Kochen oder auf die Notizen vom Nachdenken über die Möglichkeit, aus dieser Krise etwas zu machen, das nicht auf die Wiederherstellung der kaputten Realität, wie sie vorher war, abzielt. 

PS: Der Online-Stream von Loraine James’ Konzert wurde abgesagt. Sie hatte anscheinend keine Lust darauf, allein in einem Raum für eine GoPro zu spielen – und verschob die »echte« Veranstaltung auf den 14. August. 
Dazu schrieb sie: »Ok, let’s do this for real lol *fingers crossed«. I’m with her.',

(to_tsvector('Lara Scherrieble') ||
to_tsvector('Streams over streams') || 
to_tsvector('Online-Sein zu Corona-Zeiten') || 
to_tsvector('The storm gave and the storm took away, and we should look now for its gifts before the wind dies down, the waves settle and we see a wealthy white man walking out of the water.') ||
to_tsvector ('. Jack J. Halberstam, What the Storm Blows In (23.03.2020): bullybloggers.wordpress.com/2020/03/23/what-the-storm-blows-inby-jack-halberstam-for-bunkerbloggers/, zuletzt aufgerufen: 01.04.2020
. https://staythefuckhome.com/, zuletzt aufgerufen: 31.03.2020
. Fear Of Missing Out / Die Angst, etwas zu verpassen.
. Katja Grawinkel-Claassen, Der Corona-Reflex (30.03.2020): https://nachtkritik.de/index.php?option=com_content&view=article&id=17857%3Aliveness-im-digitalen-raum&catid=101&Itemid=84&fbclid=IwAR0keTRG4dly1xlw32pZTUwHosXbDGQ_nxHFa41I46fMrth7R8eRIFlWYmU, zuletzt aufgerufen: 31.03.2020
. International Indigenous Youth Council: https://www.facebook.com/search/top/?q=international%20indigenous%20youth%20council&epa=SEARCH_BOX, zuletzt aufgerufen: 01.04.2020.
. Nachdem alle Stars der kritischen Theorie von Judith Butler über Jean-Luc Nancy, Giorgio Agamben und Slavoj Žižek sich einigermaßen erfolglos daran versucht hatten. Die Texte von Cathrine Malabou (To Quarantine from Quarantine), Anne Boyer (This Virus), Jack Halberstam (What the Storm Blows In) und Paul B. Preciado (The Losers Conspiracy) sind allerdings zu empfehlen. 
. Cardi B, die sich ohnehin schon lange mit beinahe marxistischer Regierungskritik und feministischen Lyrics in mein Herz gesungen hatte, reagierte mit Humor auf den Remix ihres Posts. Sie kontaktierte den DJ Imarkkeyz und versprach in einem Tweet, die Einnahmen des Songs, die ihr zustünden, an weniger privilegierte Menschen als sie selbst zu spenden, die unter den Auswirkungen von Corona leiden werden.
. Michael Stallknecht, Die Klassikfamilie (29.03.2020): https://www.sueddeutsche.de/kultur/music-never-sleeps-nyc-die-klassikfamilie-1.4860613, zuletzt aufgerufen: 01.04.2020
. Ganz ähnlich übrigens in Deutschland: die wöchentlichen Hauskonzerte von Pianist Igor Levit. 
. Am 27. März ließ die Plattform den Künstler*innen die Beträge sogar ohne Abzüge zukommen.
. Auf Spotify zu finden unter: ebow.mp3 – STAY HOME AND STAY HEALTY *grünes herz*') || 
to_tsvector('Lara Scherrieble wurde als Teil des Kollektivs FAM_ angeboten, Online-Formate zu entwickeln, um die vereinbarte Gage für eine Veranstaltungsreihe im Grünen Salon trotz Ausfällen zu erhalten. Wahrscheinlich sagen sie zu. Scherrieble lebt in London und arbeitet als Teilzeit-DJ: soundcloud/some_lane  // tryniti')||
to_tsvector('Von Beginn des langsamen Einbruchs der Realität an, der irgendwann Anfang Februar mit den ersten Exponentialkurven in Artikeln über COVID-19 begann, war ich ununterbrochen online. Die Suche nach Informationen in unzähligen Artikeln wuchs zu einem hektischen Scrollen durch Twitter, Instagram, Tiktok und Facebook – wo es noch seltsam ruhig war, was die Coronavirus-Panik betraf. Dann, als das Thema überhandnahm – Toilettenpapier in Supermärkten ausverkauft und die ersten Bekannten an Husten erkrankt waren, gab es schlagartig kaum noch ein anderes Thema. Der Aufruf #staythefuckhome wurde zur sozialen Bewegung, Tweets aus linken und queeren Communities betrieben Aufklärung darüber, dass Zuhausebleiben, wenn man nicht gerade im Gesundheitswesen arbeitete, solidarisch war und nicht hypochondrisch. Der Stress, der mit der Entscheidung nicht mehr vor die Haustür zu gehen einherging, wurde abgelöst von dem Stress, mit allem on Track zu bleiben, was im Netz passierte. 
Empfehlungen zu Quarantäne-Aktivitäten, Fitnessanleitungen, Koch- und Backrezepten, Filme und Videogames kursierten, gleichzeitig mit Streaming-Links zu in »real life« abgesagten Lesungen, Seminaren, sogar Partys, die »auf online« verlegt werden sollten. Virtuelle Galerien eröffneten, Mitschnitte von Theaterstücken und Klassikkonzerten wurden auf Homepages veröffentlicht. Bald gab es Listen, die alle online verfügbaren Livestreams oder 24 Stunden lang verfügbare Kunstfilme sammelten, bald Verzeichnisse der Listen. Yoga from home, Online-Seminare, Virtual Reading Groups und -Hangouts: Das alles wurde zu einem völlig unübersichtlichen Kultur- und Sozialangebot. 
Am Anfang war ich euphorisch – aber dann, nach ein paar Tagen ständiger Online-fomo allein bei dem Gedanken daran, was ich im Netz alles konsumieren könnte, überfordert und genervt. 
Ich hatte den Eindruck, dass von institutioneller Seite her alles getan wurde, eine Illusion jener Normalität »vor Corona« aufrecht zu erhalten, die für viele längst Kopf stand. 
Leider machten besonders Veranstaltungen, die tatsächlich live stattgefunden hätten, online keinen Sinn mehr. Die mehrstündigen Uniseminare, die ich auf Jitsi »besuchte«, waren geprägt von technischen Problemen und schlechtem Sound, die Karte für das Konzert von Loraine James hatte ich gekauft, um sie live zu erleben. Auf Youtube hatte ich sie schon oft genug auf meinem Bildschirm gesehen. Dass das Konzert online gestreamt werden sollte, war irgendwie nett, aber stand in keinem Vergleich zu dem Event, auf das ich mich gefreut hatte. 
Laut Katja Grawinkel-Claassen bricht sich in dieser Überkompensation »der Rechtfertigungsdruck Bahnen, den öffentliche Institutionen in der neoliberalen Kultur längst vor Corona verinnerlicht haben.« Jetzt, so schreibt sie weiter, »werden häufig unausgegorene digitale Tools eingesetzt, um Angebote für das Netz zu produzieren, um die, zugespitzt gesagt, niemand gebeten hat«. Damit hat sie recht. Im Fall der Künste werden Formate, die nicht ohnehin klug mit digitalen Ästhetiken arbeiten, auch in einer globalen Pandemie nicht zu Netzkunst. Die Idee britischer Kunstuniversitäten, die Rundgänge ihrer Abschlussklassen auf einen Instagram-Kanal zu verlegen, rief zurecht eine Welle der Empörung hervor. Nicht alle können ihre Kunst der Onlinerezeption anpassen. Und niemand will noch mehr Content auf Instagram sehen. Schon gar nicht Content, der mit dem Medium nichts zu tun hat. Yoga einem Live-Stream am Rechner folgend, zu praktizieren, ist seltsam genug, wenn man wie ich Sport macht, um mal nicht am Bildschirm zu hängen. Und ins Theater gehe ich eigentlich auch, um auf eine andere Weise mit Bild und Ton involviert zu werden, als es Netflix-Serien auf meinem Rechner tun.
Gleichzeitig haben nicht nur öffentliche Institutionen neoliberale Politiken als Produktivitätsdruck verinnerlicht, sondern wir alle. Die Zeit in Quarantäne jetzt mal richtig gut nutzen, neue Sprachen lernen, mal wieder Cello spielen, sich den »Sommerbody« antrainieren, nach dem ganzen Tag im Homeoffice Kunst konsumieren und Texte runterladen, die sonst hinter Paywalls stehen – zum Glück wurde diese Haltung schnell in sämtlichen Memes als schlecht getimte Selbstoptimierung verspottet. Aber was macht man stattdessen mit der frei gewordenen Zeit?

Kinda feeling like the Earth just sent us all to our rooms to think about what we’ve done.
Dieser Satz auf der Facebook-Seite des International Indigenous Youth Council brachte mein Bedürfnis nach Ruhe zwischen gefühltem Freizeit-Overload und leichter Panik angesichts der stündlich wechselnden Informationslage auf den Punkt. Dem Ausnahmezustand in der Corona-Pandemie konnte nicht mit mehr Internet-Snacks und Kunst auf Abruf begegnet werden. Was vor Corona Normalität war – arbeiten oder zur Schule gehen, Freund*innen in Bars oder Clubs treffen etc. – war vorübergehend suspendiert. Plötzlich waren alle, die Zugang zu Basic Needs wie einem eigenen Zimmer haben, allein darin eingesperrt. Und konnten von da aus auf den vollständigen Zerfall dessen schauen, was vorher schon kaputt war. Europäische Außenpolitik. Das privatisierte Bildungs- und Gesundheitssystem. Zeitarbeit. Rassismuskritische Berichterstattung (viel zu wenig). Das Einkommen von Care-Arbeiter*innen und Künstler*innen (viel zu wenig). Etc. 
Dafür braucht man Zeit. Allein, um zu realisieren, dass das System um einen herum, das aus aktivistischer Perspektive oft so unumstürzlich scheint, kontingent gesetzt werden kann – in diesem Fall leider nicht durch die zahlreichen politischen Kämpfe des letzten Jahrzehnts, sondern durch eine Krankheit.  Streamen und Hören   Der erste musikalische Beitrag, der sich inhaltlich explizit auf Corona bezieht und gut geraten ist, kam aus dem Bereich der Memes und der Popmusik; aus einer zufälligen Fusion von Instagram und TikTok-Formaten. Ein (zuvor) unbekannter DJ sampelte einige Tage vor dem offiziellen Lockdown in Deutschland Cardi B, eine der erfolgreichsten US-Rapperinnen, mit einem selbstgebastelten Beat und ein paar Tanzvideos. Zu sehen ist ein kurzer Ausschnitt aus Cardi Bs Instagram Post, in dem sie, (in einem halbdurchsichtigen Kleid und azurblauen 5cm-Nägeln in ihrer Küche stehend) ruft: »Guess what bitch, ha ha ha! Coronavirus! Coronavirus! Shit is real, shit is getting real«. Dann setzt ein simpler Hip-Hop Beat ein, Cardi Bs Worte werden repetitiv dazu gemixt und die nächsten 60 Sekunden tanzen unter anderem das Krümelmonster, Beyoncé, Bugs Bunny und ein paar Privatpersonen exzessiv zu dem Song.
Nachdem ich das Video circa zehnmal anschauen und jedes Mal wieder lachen musste – war es vielleicht sogar das erste Mal richtig lachen seit der ersten Virus-Panikwelle? – und der Ohrwurm Shit is real, Shit is getting real mich tagelang verfolgte, war ich mir sicher: dieses auditive Meme war der bislang beste Kommentar zur aktuellen Lage. 	
Dass der Song Coronavirus nach ein paar Tagen auf Platz 1 der Itunes Charts in den USA landete, war nicht weiter verwunderlich.
Auf italienischen Balkonen wurde unterdessen zusammen gesungen, in einer Kleinstadt im Süden des Landes ein DJ-Pult mit Lightshow aufgebaut und die Straße mit Gigi D’Agostino’s Disco Hit L‘amour toujours beschallt. Während die wackeligen Aufnahmen dieser Szenen mich tatsächlich rührten, nicht nur weil ich dort aufgewachsen bin, sondern auch weil es dabei weder um den gemeinsamen Musikgeschmack der Nachbar*innen, noch um die Übertragung und Rezeption des Moments ging, war ich gegenüber Projekten, die die »Kraft der Musik« heraufbeschwörten eher skeptisch. 
Das Projekt Music Never Sleeps NYC zum Beispiel versammelte Stars der klassischen Musik, die eine ganze Nacht lang in einem Musik-Marathon ihre Lieblingsstücke spielten – von ihren privaten Wohnungen aus. Laut des Organisators hatten er selbst und die eingeladenen Künstler*innen damit »endlich wieder einen Lebenssinn«. Auf den ersten Blick eine ehrenvolle künstlerische Aktion, wirkt das ganze doch sehr sendungsbewusst – und hinsichtlich der wohlhabenden Teilnehmenden doch eher wie ein Charityball zu eigenen Ehren. Wenn der Sound sowieso aus der kleinen Anlage Zuhause kommt und nicht aus Instrumenten, in deren unmittelbarer Nähe ich mich befinde, funktioniert es für mich ehrlich gesagt besser, die Klaviersonate von Bach zu hören, ohne dabei in Wohnzimmer der oberen Mittelklasse zu blicken. 
Während Music Never Sleeps NYC einen leichten Hauch der Titanic-Band hat, die auf dem unausweichlich sinkenden Schiff tapfer weiterspielt, widersetzt sich die Balkonmusik in Italien der Annahme, dass das Schiff untergeht. Außerdem drängt sich mir bei dem Titanic-Vergleich die Frage auf, für wen das Schiff bald sinken könnte. Sicherlich nicht für reiche Klassik-Fans. 

Hören ohne streamen
Was ist also der Ausweg aus der Zwickmühle zwischen unangenehm ambitionierten Streamingprojekten einerseits und nachbarschaftlichen Physical-Distance-Jams, wenn man nicht gerade in italienischen Städten lebt? (Im italophilen Deutschland wurde ein paar Tage später etwas Ähnliches mit Beethovens »Ode an die Freude« probiert – lieber nicht angucken.) 
Playlisten. 
Und zwar entweder von Freund*innen: Zu hören, was eine gute Freundin Zuhause am liebsten hört, ist nämlich zugleich intim und eine große Hilfe, wenn man die eigene Musikauswahl schon zu oft gehört hat und keine Lust hat, stundenlang nach neuen Tracks zu suchen. Um selbst welche zu basteln: Seit romantischem CD-Brennen zu Teenzeiten haben das ja viele lange nicht mehr gemacht – kann man etwa auf Bandcamp Musik kaufen. Musiker*innen verdienen so ein wenig Geld, während sie keine Konzerte geben und hoffentlich vorübergehend von den in ein paar Ländern anberaumten Förderungspaketen leben können. 
Oder Playlisten, die von Künstler*innen zusammengestellt wurden – und auch ohne Corona gut gewesen wären: Der britische Produzent Dean Blunt veröffentlichte still und leise eine neue archivarische Sammlung von Aufnahmen aus den letzten acht Jahren unter dem Titel Roaches 2012-2019 auf Spotify. Michelle Gurevich stellte 7pm Selects zusammen, die Playlist ist aber auch für Morgende sehr zu empfehlen. Rapperin Ebow, Sängerin Slimgirl Fat und senu_unofficial aka beverlybarcley veröffentlichten Spotify-Playlisten mit ihren persönlichen Quarantine-Best-Ofs. The ultimate chilled house cat tunes ist gerade eine meiner Lieblingslisten, weil sich genau die Art entspannter und beruhigender Musik darin findet, die ich sonst viel zu selten höre. 
Playlisten trösten über Einsamkeit hinweg, aber lassen einen in Ruhe; und woanders hin schauen als auf den Laptop – z.B. auf die Straße beim Weg zum Einkauf für die kranke Nachbarin, auf den Suppentopf beim Kochen oder auf die Notizen vom Nachdenken über die Möglichkeit, aus dieser Krise etwas zu machen, das nicht auf die Wiederherstellung der kaputten Realität, wie sie vorher war, abzielt. 

PS: Der Online-Stream von Loraine James’ Konzert wurde abgesagt. Sie hatte anscheinend keine Lust darauf, allein in einem Raum für eine GoPro zu spielen – und verschob die »echte« Veranstaltung auf den 14. August. 
Dazu schrieb sie: »Ok, let’s do this for real lol *fingers crossed«. I’m with her.')));

